// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsaukqkoekekodivewbi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzYXVrcWtvZWtla29kaXZld2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODI3MzUsImV4cCI6MjA2NTU1ODczNX0.5hbMGkeyLZXHqSxA3YgviyDT0zZbOYOR7zgYmGAsHZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});